---
layout: devbookchapter
summary: Explains how Jenkins routes HTTP requests, and what ways to respond exist.
---
:author:
:description:
:email: jenkinsci-users@googlegroups.com
:notitle:
:sectanchors:
:toc: left

= Handling Requests

Let's look at some real-world examples for the most common ways to process (part of) the path:

* Traversing the model graph
  - Getter: +/*log*/…+ → +jenkinsdoc:jenkins.model.Jenkins#getLog%28%29[Jenkins#getLog()]+
  - Getter with argument: +/*job/foo*/…+ → +jenkinsdoc:hudson.model.Hudson#getJob%28java.lang.String%29[Hudson#getJob("foo")]+
  - Dynamic getter: +/job/foo/*1*/…+ → +jenkinsdoc:hudson.model.Job#getDynamic%28java.lang.String,%20org.kohsuke.stapler.StaplerRequest,%20org.kohsuke.stapler.StaplerResponse%29[Job#getDynamic("1", …)]+
* Rendering views
  - Index view: +/job/foo*/*+ → *'index.jelly'* of +'jenkinsdoc:Job[]'+ (or other jenkinsdoc:TopLevelItem[] implementations)
  - Named view: +/job/foo/*changes* → *'changes.jelly'* of +'jenkinsdoc:Job'+
* Action methods
  - Action method
    - +/job/foo/1/*artifact*+ → +jenkinsdoc:hudson.model.Run#doArtifact%28%29[Run#doArtifact(…)]+
    - +/job.foo/*config.xml*+ → +jenkinsdoc:hudson.model.AbstractItem#doConfigDotXml%28org.kohsuke.stapler.StaplerRequest,%20org.kohsuke.stapler.StaplerResponse%29[@WebMethod("+config.xml+") doConfigDotXml(…)]

Additionally, objects can implement several interfaces to further control how Stapler processes URLs:

* `StaplerProxy` allows delegating the processing of a URL to another object. So, for `/foo/bar`, if `getFoo()` returns an object `x` that implements `StaplerProxy`'s `getTarget()` method, Stapler will call `x.getTarget()` and continue using that to process the rest of the URL (`bar`). This has the *highest priority* among all possible URL processing options. `getTarget()` may also return `this`, for example to implement permission checks: No getters or views of `x` will be available to anyone who doesn't have the necessary permissions via URLs.
* `StaplerOverridable` is an interface TODO
* `StaplerFallback` allows delegating the processing of a URL to another object, similar to `StaplerProxy`, but has the *lowest priority* among all possible URL processing options.

For more information on how Stapler binds (or staples) a Java Object Model to a URL hierarchy, see the [Stapler Reference Documentation|http://stapler.kohsuke.org/reference.html]
