---
:layout: post
:title: First successful use of telemetry in Jenkins
:tags:
- core
- security
- telemetry
:author: daniel-beck
---

Half a year ago, on December 5 2018, we delivered a security fix for Jenkins that had the potential to break _everything_.
We needed to change how Jenkins, through the Stapler web framework, handled requests, tightening the rules around what requests would be processed by Jenkins.
In the six months since, we didn't receive any reports of problems resulting from this change, and it's thanks to the telemetry we gathered beforehand.

== The Problem

Jenkins uses the Stapler web framework for HTTP request handling.
Stapler's basic premise is that it uses reflective access to code elements matching its naming conventions.
For example, any public method whose name starts with `get`, and that has a `String`, `int`, `long`, or no argument can be invoked this way on objects that are reachable through these means.
As these naming conventions closely match common code patterns in Java, accessing crafted URLs could invoke methods never intended to be invoked this way.

A simple example of that is a URL every Jenkins user would be familiar with: `/job/jobname`.
This ends up invoking the a method called `#getJob(String)`, with the argument being `"jobname"`, on the root application object, and having it handle the rest of the URL, if any.
Of course, this is a URL intended to be accessed this way.
How about `Object#getClass()`, followed by `Class#getClassLoader()`?
We identified a number of URLs that could be abused to access otherwise inaccessible jobs, or even invoke internal methods in the web application server to invalidate all sessions.

== The Idea

To solve this problem inherent in the Stapler framework's design, we defined rules that restrict invocation beyond what would be allowed by Stapler.
For example, the declared return type of getters now needed to be one defined in Jenkins core or a Jenkins plugin.
Otherwise, the type wouldn't be aware of Stapler, and couldn't produce a meaningful response anyway.

This meant that getters just declaring `Object` (or `List`, `Map`, etc.) would no longer be allowed by default.
It was clear to the developers working on this problem that we needed the ability to be able to override the default rules for specific getters.
But allowing plugin developers to adapt their plugins after we published the fix wasn't going to cut it;
Jenkins needed to ship with a comprehensive default whitelist for methods known to not conform to the new rules, so that updating would not result in problems for users.

== The Solution

While there is tooling like https://github.com/jenkinsci/plugin-compat-tester/[Plugin Compatibility Tester] and https://github.com/jenkinsci/acceptance-test-harness[Acceptance Test Harness], many Jenkins plugins do not have comprehensive tests of their UI -- the Jenkins UI is fairly stable after all.
We did not expect to have sufficient test coverage to deliver a change like this.
The only way we would be able to build such a comprehensive whitelist would be to add telemetry to Jenkins.

While Jenkins instances periodically report usage statistics to the Jenkins project, the information included is very bare bones and mostly useful to know the number of installations, the popularity of plugins, and the general size of Jenkins instances through number and types of jobs and agents.
We also didn't want to just collect data without a clear goal, so we set ourselves some limitations -- collect as little data as possible, no personally identifiable information, have a specific purpose for each kind of information we would collect, and define an end date for the collection in advance.
We defined all of this in https://github.com/jenkinsci/jep/blob/master/jep/214/README.adoc[JEP-214], created the https://github.com/jenkins-infra/uplink[Uplink service that would receive submissions], and added the basic client framework to Jenkins.
The implementation is fairly basic -- we just submit an arbitrary JSON object with some added metadata to a service.
This system would inform tweaks to a security fix we were anxious to get out, after all.

Starting in mid October for  weekly releases, and early November for LTS, tens of thousands of Jenkins instances would submit Stapler request dispatch telemetry daily, and we would keep identifying code incompatible with the new rules and amending the fix.
Ultimately, https://github.com/jenkinsci/jenkins/blob/44c4d3989232082c254d27ae360aa810669f44b7/core/src/main/resources/jenkins/security/stapler/default-whitelist.txt[the whitelist] would include more than 30 entries, preventing serious regressions in popular plugins like plugin:credentials[Credentials Plugin], plugin:junit[JUnit Plugin], or the Pipeline plugins suite, down to plugin:google-cloud-health-check[Google Health Check Plugin], a plugin with just 80 installations when we published the fix.

Learning what requests would result in problems also allowed us to write better developer documentation -- we already knew what patterns of code would break, and how popular each of them was in the plugin ecosystem.

== The Overhaul

I wrote above:

____
For example, the declared return type of getters now needed to be one defined in Jenkins core or a Jenkins plugin.
____

While this was part of the first version of the fix, it isn't how the fix that we published actually works.
About a month before the intended release date, internal design/code review feedback criticized the unnecessarily complicated and time-consuming implementation that at the time required scanning the class path of Jenkins and all plugins and inspecting the classes on it.

So we tried to require that the declared type or any of its ancestors be annotated with `@StaplerAccessibleType`, annotated a bunch of types in Jenkins itself (`ModelObject`), and ran our scripts that check to see whether Stapler would be allowed to dispatch methods identified in telemetry.
We'd long since automated the daily update of dispatch telemetry processing, so it was a simple matter of changing which Jenkins build we were working with.

The results were very positive -- very few additional types needed whitelisting, while many more were no longer (unnecessarily) allowed to be dispatched to.
This very late experiment was essentially the fix we delivered.
We didn't need to scan the classpath, we didn't need to perform costly scanning of the class path on startup, and the rules governing request dispatch in Stapler, while different from before, are pretty easy to understand.

== The Verdict

As usual when delivering a fix we expect could result in numerous regressions, we https://wiki.jenkins.io/display/JENKINS/Plugins+affected+by+the+SECURITY-595+fix[created a wiki page] that users could report problems on.
The only entry on that wiki page is something we were aware of well before release, and the affected, undocumented feature in Git Plugin ended up being removed anyway.
In the six months since we released the update, no further entries were added.

Without telemetry, delivering a fix like this one would have been difficult to begin with.
Tinkering with the implementation just a few weeks before release and not getting any negative user feedback?
This would be impossible.
